In [1]:
import torch

$$
x = 3, y = 4\\
z = x^2 + y^2
$$

In [2]:
x = torch.tensor(3.0, requires_grad=True)
y = torch.tensor(4.0, requires_grad=False)

In [3]:
z = torch.pow(x, 2)+torch.pow(y, 2)

In [4]:
print(x.requires_grad)

True


In [5]:
print(y.requires_grad)

False


In [6]:
print(z.requires_grad)

True


求导，通过backward函数来实现

In [4]:
z.backward()

In [5]:
print(x.grad)

tensor(6.)


In [6]:
print(y.grad)

None


## version 2

矩阵点乘
$$
a \cdot b = \sum_{i=1}^{n} a_i \cdot b_i
$$

In [10]:
x = torch.arange(4.0)
x.requires_grad_(True)
x.grad # 默认值为None
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [12]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [13]:
# 求导
# 通过反向传播函数来自动计算y关于x的每个分量的梯度
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [14]:
# 验证
x.grad == 4*x

tensor([True, True, True, True])

In [15]:
# 在默认情况下，pytorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [17]:
# 对于非标量调用backward需要传入一个gradient参数
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [19]:
x.grad.zero_()
y = x * x
# detach()是把y看作一个常数
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [21]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])